#!/bin/bash

. ../run.common

PROJ=$1

TMP=WORK/"$PROJ".tmp
OUT=WORK/"$PROJ".out

echo "==== $PROJ"
$JSBATCH -f PROJ/$PROJ.proj -oprec 4 -optim \
   -i model.optim.calcCovMat=true -oreport > $TMP

N=`cat -n $TMP | fgrep Parm | awk '{ print $1 }'`
N=$(($N-1))
M=`cat -n $TMP | fgrep "run#" | awk '{ print $1 }'`
sed "$M",999d $TMP | sed 1,"$N"d > $OUT
rm $TMP
   


