#!/bin/sh

. ../run.common

rm -Rf WORK
mkdir WORK

cd PROJ
PROJS=`ls *.proj | sed s/.proj//g`
cd ..

if [ $# -ne 0 ]
then
  PROJS="$*"
fi

for p in $PROJS
do
  run1 $p
done

cd MODBAD
MODBAD=`ls *.mod | sed 's/\.mod//'`
cd ..

for i in $MODBAD
do
  run1bad $i
done

cd PROJBAD
PROJBAD=`ls *.proj | sed 's/\.proj//'`
cd ..

for i in $PROJBAD
do
  run1badp $i
done

