#!/bin/sh

if [ $# != 2 ]
then
  echo "usage: diffall dir1 dir2"
  exit 1
fi

DIR1=$1
DIR2=$2
DSW="-b --ignore-matching-lines version --ignore-matching-lines jsim/work"

cd $DIR1
for i in *.out
do
  echo "====================== $i"
  diff $DSW $i ../$DIR2
done
