#!/bin/sh
#  run verify dirs, compare or diff results with reference data

. run.common

# diff or cmp?
CMP=0
if [ "$1" = "-c" ]
then
  CMP=1
  shift
fi

# set DIRS
if [ $# == 0 ]
then
  DIRS=`ls */runall | awk -F / '{ print $1 }'`
elif [ "$1" = "win32" ]
then
  DIRS=`ls */runall | awk -F / '{ print $1 }' | sed /xsim/d | sed /fpack/d | sed /xfunc/d`
  shift
  DIRS="$DIRS $*"
else
  DIRS="$*"
fi

doit () {
  for i in $DIRS
  do
    echo "============================ STARTING DIR $i"
    cd $i
    ./runall
    if [ $CMP -eq 1 ]
    then
      ../cmpall REF WORK
    else
      ../jsdiffall REF WORK
    fi
    cd ..
  done
}

doit 2>&1 | tee log 
