#!/bin/sh

. ../run.common

echo ==== $1

if [ $# -ne 4 ]
then
  echo "Usage: fpack/run1 model time cin cout"
  exit 1
fi
MODEL="$1"
TIME="$2"
CIN="$3"
COUT="$4"

PROJFILE=$JSFPACK/"$MODEL".proj
CINEXPR="$CIN"="exp(-""$TIME"")"

$JSBATCH -f "$PROJFILE" -i "$CINEXPR" -o $CIN $COUT \
  -ozero 1e-6 -oprec 4 -ofmt column -out WORK/"$1".out -stack

