#!/bin/sh

cd MOD
MODS=`ls *.mod | sed -e 's/\.mod//'`
cd ..

cd MODBAD
MODBADS=`ls *.mod | sed -e 's/\.mod//'`
cd ..

cd MODWARN
MODWARNS=`ls *.mod | sed -e 's/\.mod//'`
cd ..

rm -Rf WORK
mkdir WORK

for i in $MODS
do
  run1 $i
done

for i in $MODWARNS
do
  run1warn $i
done

for i in $MODBADS
do
  run1bad $i
done



