MODEL= mmid4
SRCS_F= cout.F    hetmod.F  mXid4.F  \
	optdcn.F  psghet.F  run.F \
	decnvl.F  msnput.F  mXid4_util.F \
	parmod.F  q.F       vasop.F
SRCS_f= bn58.f  bn59.f  hetfnc.f
SRCS_c= 
MODEL_DFLAGS=-Dmmid4

vpath %.F ../mxid4
vpath %.f ../mxid4
include ../Makefile.model

