#!/bin/sh

rm -Rf WORK
mkdir WORK

cd MOD
MOD=`ls *.mod | sed 's/\.mod//'`
cd ..

for i in $MOD
do
  for j in Auto Dopri5 Radau KM Fehlberg Euler RK2 RK4 CVode
  do
    k="$i"_"$j"
    echo ==== $k
    $JSBATCH -f MOD/"$i".mod -i solver.ode_which=$j -out WORK/$k.out
  done
done

for i in vanderpol
do
  echo ==== $i
  $JSBATCH -f MODRADAU/"$i".mod -oprec 4 -ofmt column -o y1 y2 -out WORK/$i.out
done

cd MODBAD
MODBAD=`ls *.mod | sed 's/\.mod//'`
cd ..

for i in $MODBAD
do
  run1bad $i
done

