/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JSim_nml_opt_NL2sol */

#ifndef _Included_JSim_nml_opt_NL2sol
#define _Included_JSim_nml_opt_NL2sol
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JSim_nml_opt_NL2sol
 * Method:    nl2sol
 * Signature: (ILJSim/jruntime/RTContext;II[D[II[DI[DII[I)V
 */
JNIEXPORT void JNICALL Java_JSim_nml_opt_NL2sol_nl2sol
  (JNIEnv *, jobject, jint, jobject, jint, jint, jdoubleArray, jintArray, jint, jdoubleArray, jint, jdoubleArray, jint, jint, jintArray);

/*
 * Class:     JSim_nml_opt_NL2sol
 * Method:    abort
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_JSim_nml_opt_NL2sol_abort
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
