SRCS_F=  
SRCS_f= nl2sol.f \
	dassst.f  dfdhes.f  dlivmu.f  dltvmu.f  nl2sol.f  dslupd.f dvaxpy.f \
        dglrit.f  dlmstp.f  dlupdt.f  dslvmu.f  dvdflt.f \
        ddbdog.f  dgqtst.f  dlnvrt.f  dlvmul.f  doprds.f  dsmsno.f  dvscpy.f \
        ddeflt.f  dhumit.f  dlsqar.f  dmlprp.f  dparck.f  dsnoit.f  dvvmup.f \
        dhumsl.f  dlsqrt.f  dnl2cp.f  dqradr.f  dstopx.f  dwzbfg.f \
        ddupd2.f  ditsum.f  dlsvmn.f  dnl2it.f  drelst.f  dsumit.f \
        ddupdu.f  dlitvm.f  dltsqr.f  dnl2rd.f  dsgrd2.f  dsumsl.f

SRCS_c= jnl2sol.c

include ../../Makefile.global.nml


