/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JSim_nml_opt_GGopt */

#ifndef _Included_JSim_nml_opt_GGopt
#define _Included_JSim_nml_opt_GGopt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JSim_nml_opt_GGopt
 * Method:    ggopt
 * Signature: (ILJSim/jruntime/RTContext;I[DII[D[D[D[D[D[IIII[D[D[D[D[D[D[D)V
 */
JNIEXPORT void JNICALL Java_JSim_nml_opt_GGopt_ggopt
  (JNIEnv *, jobject, jint, jobject, jint, jdoubleArray, jint, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jintArray, jint, jint, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     JSim_nml_opt_GGopt
 * Method:    abort
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_JSim_nml_opt_GGopt_abort
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
