
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Aug 12 11:49:35 PDT 2013
//----------------------------------------------------

package JSim.expr;

/** CUP generated class containing symbol constants. */
public class ExprParserSym {
  /* terminals */
  public static final int TIMES = 6;
  public static final int AND = 17;
  public static final int LT = 13;
  public static final int NE = 12;
  public static final int IDENT = 25;
  public static final int ELSE = 20;
  public static final int PLUS = 5;
  public static final int OR = 18;
  public static final int RPAREN = 3;
  public static final int TRUE = 22;
  public static final int IF = 19;
  public static final int LPAREN = 2;
  public static final int GT = 15;
  public static final int LE = 14;
  public static final int COMMA = 4;
  public static final int NUMBER = 24;
  public static final int EOF = 0;
  public static final int DIVIDE = 8;
  public static final int DERIV = 10;
  public static final int PI = 21;
  public static final int FALSE = 23;
  public static final int GE = 16;
  public static final int MINUS = 7;
  public static final int error = 1;
  public static final int EQ = 11;
  public static final int POWER = 9;
}

