
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Aug 12 11:49:35 PDT 2013
//----------------------------------------------------

package JSim.expr;

/** CUP generated class containing symbol constants. */
public class PrettyUnitParserSym {
  /* terminals */
  public static final int MINUS = 4;
  public static final int DIVIDE = 6;
  public static final int NUMBER = 8;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int RPAREN = 3;
  public static final int TIMES = 5;
  public static final int POWER = 7;
  public static final int LPAREN = 2;
  public static final int NAME = 9;
}

