#!/bin/sh

. ../run.common

echo ==== $1 bad

TMP=WORK/"$1".tmp
OUT=WORK/"$1".bad.out
$JSBATCH -f XML*/"$1".cellml -oplan > $TMP 2>&1
STAT=$?
sed -e "/JSim version/d" $TMP > $OUT
rm $TMP

if [ $STAT -eq 0 ]
then
  echo "  Program incorrectly exited without error"
fi
