#!/bin/sh

. ../run.common

cd PROJ
PROJS=`ls *.proj | sed -e 's/.proj//'`
cd ..

rm -Rf WORK
mkdir WORK

for i in $PROJS
do
  run1 $i
done

run1nan uv1  w
run1nan int2 v

echo "==== mod tests"
  $JSBATCH -f MOD/tx2.mod -o "u(1.3,t)" -ofmt pretty > WORK/mod1.out
  $JSBATCH -f MOD/tx2.mod -o  "u(x,1.3)" -ofmt pretty > WORK/mod2.out
  $JSBATCH -f MOD/tx2.mod -o "u(y,y)" -ofmt pretty -i y.min=-1 y.max=8 > WORK/mod3.out

