#!/bin/sh

cd MOD
MODS=`ls *.mod | sed -e 's/.mod//'`
cd ..

rm -Rf WORK
mkdir WORK


echo "==== memloops"
$JSBATCH -f PROJ/memloop.proj -loops -o a > WORK/memloops.out

for i in $MODS
do
  run1 $i
done
