/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JSim_nml_ode1_ODE1SolverDopri5 */

#ifndef _Included_JSim_nml_ode1_ODE1SolverDopri5
#define _Included_JSim_nml_ode1_ODE1SolverDopri5
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JSim_nml_ode1_ODE1SolverDopri5
 * Method:    jdopri5
 * Signature: (ILJSim/jruntime/RTContext;IDD[D[DDDJJDDDDDLJSim/nml/ode1/ODE1Callbacks;)I
 */
JNIEXPORT jint JNICALL Java_JSim_nml_ode1_ODE1SolverDopri5_jdopri5
  (JNIEnv *, jobject, jint, jobject, jint, jdouble, jdouble, jdoubleArray, jdoubleArray, jdouble, jdouble, jlong, jlong, jdouble, jdouble, jdouble, jdouble, jdouble, jobject);

#ifdef __cplusplus
}
#endif
#endif
