#!/bin/sh

rm -Rf WORK
mkdir WORK

runflat

cd MOD
MODS=`ls *.mod | sed -e 's/.mod//'`
cd ..

for i in $MODS
do
  run1 $i
done

cd MODINJ
MODS=`ls *.mod | sed -e 's/.mod//'`
cd ..

for i in $MODS
do
  runinj $i
done

