#!/bin/bash

rm -Rf WORK
mkdir WORK

cd MOD
MODS1=`ls *.mod | sed -e 's/.mod//'`
cd ..


cd MODINJ
MODS2=`ls *.mod | sed -e 's/.mod//'`
cd ..


for i in $MODS1 $MODS2
do
  echo ====== $i flat
  M=`ls MOD*/"$i".mod`
  $JSBATCH -f $M -oflat > WORK/"$i"flat.out
done


