/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JSim_nml_opt_Simplex */

#ifndef _Included_JSim_nml_opt_Simplex
#define _Included_JSim_nml_opt_Simplex
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JSim_nml_opt_Simplex
 * Method:    simplx
 * Signature: (ILJSim/jruntime/RTContext;I[D[D[D[D[DI[D[D[I[D[I[D[D[I[D[D[D)V
 */
JNIEXPORT void JNICALL Java_JSim_nml_opt_Simplex_simplx
  (JNIEnv *, jobject, jint, jobject, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jint, jdoubleArray, jdoubleArray, jintArray, jdoubleArray, jintArray, jdoubleArray, jdoubleArray, jintArray, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     JSim_nml_opt_Simplex
 * Method:    abort
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_JSim_nml_opt_Simplex_abort
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
