/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JSim_nml_ode1_ODE1SolverRadau */

#ifndef _Included_JSim_nml_ode1_ODE1SolverRadau
#define _Included_JSim_nml_ode1_ODE1SolverRadau
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JSim_nml_ode1_ODE1SolverRadau
 * Method:    jradau
 * Signature: (ILJSim/jruntime/RTContext;IDD[D[DDDIIIIIDDDDDDDDDDDLJSim/nml/ode1/ODE1Callbacks;)I
 */
JNIEXPORT jint JNICALL Java_JSim_nml_ode1_ODE1SolverRadau_jradau
  (JNIEnv *, jobject, jint, jobject, jint, jdouble, jdouble, jdoubleArray, jdoubleArray, jdouble, jdouble, jint, jint, jint, jint, jint, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jobject);

#ifdef __cplusplus
}
#endif
#endif
