#!/bin/sh

. jsbuild.osarch

. ../run.common

echo "==== $1"

MODEL=$1
shift
OUTPUT=$1
shift
OBJECTS="$*"

# build $MODEL.o
rm -f "$MODEL".o
make -f $JSXMAKEFILE "$MODEL".o

$JSXWRAP -f $MODEL "$MODEL".o $OBJECTS

$JSBATCH -f "$MODEL".mod -oprec 7 -ofmt column -o $OUTPUT > WORK/"$MODEL".out


