#!/bin/sh

. ../run.common

if [ $# -lt 3 ]
then
  echo "Usage: run1ode nproc proj solver output [inputs]"
  exit 1
fi
NPROC=$1
shift
PROJ=$1
shift
SOLVER=$1
shift
OUTPUT=$1
shift
INPUTS="$*"
OUT=WORK/"$PROJ"_$SOLVER.out
LOG=LOG/"$PROJ"_"$SOLVER".log

echo "== Fzero $NPROC $PROJ $SOLVER $OUTPUT $INPUTS"

if [ ! -d WORK ]
then
  mkdir WORK
fi

FINPUTS="solver.fzero_bound=$SOLVER"
if [ "$SOLVER" = "ggopt" -o "$SOLVER" = "neldermead" -o "$SOLVER" = "nl2sol" ]
then
  FINPUTS="$FINPUTS solver.fzero_unbound=$SOLVER"
fi
if [ "$SOLVER" = "linear" ]
then
  FINPUTS=
fi

$JSBATCH -f PROJ/"$PROJ".proj -loops -o $OUTPUT -timing \
  -mpdebug $NPROC -oprec 4 -out $OUT -i $INPUTS $FINPUTS \
  > $LOG 2>&1  
STAT=$?

if [ $STAT -eq 0 ]
then
  cat $LOG
else 
  echo "  $SOLVER returned status $STAT"
fi

rm -Rf hs_err*.log

