#!/bin/bash

. ../run.common

if [ $# -lt 4 ]
then
  echo "Usage: run1opt nproc proj solver outputs"
  exit 1
fi
NPROC=$1
shift
PROJ=$1
shift
SOLVER=$1
shift
OUTPUTS="$*"

OUT=WORK/"$PROJ"_$SOLVER.out
LOG=LOG/"$PROJ"_"$SOLVER".log

echo "== OPT $NPROC $PROJ $SOLVER"

if [ ! -d WORK ]
then
  mkdir WORK
fi

$JSBATCH -f PROJ/"$PROJ".proj -optim -o $OUTPUTS -timing \
  -mpdebug $NPROC -oprec 4 -out $OUT -i model.optim.alg=$SOLVER \
  > $LOG 2>&1  
STAT=$?

if [ $STAT -eq 0 ]
then
  cat $LOG
else 
  echo "  $SOLVER returned status $STAT"
fi

rm -Rf hs_err*.log

