#!/bin/sh

. ../run.common

if [ $# -ne 3 ]
then
  echo "Usage: run1fim nproc proj data"
  exit 1
fi

NPROC=$1
PROJ=PROJ/"$2"
DATA=DATA/$3

OUT=WORK/fim_`echo $2 | sed 's/.proj$/.out/'`

echo == FIM $2 
$JSFIM -silent -mpdebug $NPROC $PROJ $DATA > $OUT
