#!/bin/sh

. ../run.common

MOD=$1
shift
ALG=$1
shift
XARGS="$*"

OUT=WORK/"$MOD"_"$ALG".out

INPUTS="solver.fzero_bound=$ALG"
if [ "$ALG" = "ggopt" -o "$ALG" = "neldermead" -o "$ALG" = "nl2sol" ]
then
  INPUTS="$INPUTS solver.fzero_unbound=$ALG"
fi


echo ==== $MOD $ALG
$JSBATCH -f MOD/"$MOD".mod -i $INPUTS -oprec 5 -out $OUT $XARGS
STAT=$?

if [ $STAT -ne 0 ]
then
  echo "Program exited with error status"
fi
