/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class RTXMatlab */

#ifndef _Included_RTXMatlab
#define _Included_RTXMatlab
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     RTXMatlab
 * Method:    connect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_RTXMatlab_connect
  (JNIEnv *, jobject);

/*
 * Class:     RTXMatlab
 * Method:    setValue
 * Signature: (Ljava/lang/String;[[D)V
 */
JNIEXPORT void JNICALL Java_RTXMatlab_setValue
  (JNIEnv *, jobject, jstring, jobjectArray);

/*
 * Class:     RTXMatlab
 * Method:    runCommand
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_RTXMatlab_runCommand
  (JNIEnv *, jobject, jstring);

/*
 * Class:     RTXMatlab
 * Method:    getValue
 * Signature: (Ljava/lang/String;)[[D
 */
JNIEXPORT jobjectArray JNICALL Java_RTXMatlab_getValue
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
