#!/bin/bash

rm -Rf WORK
mkdir WORK

. ../run.common

run1 body time Cin1 chead
run1 btex20 time Cin Cout
run1 btex40 time Cin Cout
run1 gentex time Cin_v Cout_v
run1 gentex2 time Cin_v Cout_v
run1 mhed time Cin Cout
run1 mmid4 time Cin_vascular Cout_v
run1 msid4 time Cin_vascular Cout_v
