/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JSim_nml_ode1_ODE1SolverCVode */

#ifndef _Included_JSim_nml_ode1_ODE1SolverCVode
#define _Included_JSim_nml_ode1_ODE1SolverCVode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JSim_nml_ode1_ODE1SolverCVode
 * Method:    jcvode
 * Signature: (ILJSim/jruntime/RTContext;IDD[D[DDDIZLJSim/nml/ode1/ODE1Callbacks;)I
 */
JNIEXPORT jint JNICALL Java_JSim_nml_ode1_ODE1SolverCVode_jcvode
  (JNIEnv *, jobject, jint, jobject, jint, jdouble, jdouble, jdoubleArray, jdoubleArray, jdouble, jdouble, jint, jboolean, jobject);

#ifdef __cplusplus
}
#endif
#endif
