#!/bin/bash

rm -Rf WORK
mkdir WORK

# I4 bullseyes
run1 i4a -ofmt i4bull -ref R1 PROJ/exp1.proj DATA/ref.tac 
run1 i4b -ofmt i4bull -ref R1 -fgen Cin=R1s1 PROJ/Cin0.proj DATA/ref.tac 
run1 i4c -ofmt i4bull -ref R1 -fgen Cin=R1s1 PROJ/Cin1.proj DATA/ref.tac 

# J4 columnar data
run1 j4a PROJ/exp1.proj DATA/ref.cdata
run1 j4b -fgen Cin=seg1 PROJ/Cin0.proj DATA/ref.cdata
run1 j4c -fgen DATA/input.cdata Cin=input PROJ/Cin0.proj DATA/ref.cdata

