MODEL= gentex
SRCS_F= decnvl.F  ebtxgsubs.F  gentex.F  msnput.F  q.F    runref.F \
	ebtxg.F   ectxg.F      hetmod.F  parmod.F  run.F  source.F \
	scprng.F
SRCS_f= dc_decsol.f  dopri5.f  ebtx20.f  etex59.f  matxtc.f  ptools.f  setz.f \
	dcnopt.f     ebldop.f  ebtx30.f  hetfnc.f  mtype.f   radau.f   snsnew.f \
	decsol.f     ebtx10.f  ectx30.f  numreg.f  regarr.f
SRCS_c= etex59c.c  scmaloc.c


include ../Makefile.model

