#!/bin/bash

. ../run.common

echo ==== $1 data

$JSBATCH -f TXT/"$1".txt -i time.max=10 time.delta=.5 -out WORK/"$1"_data.out
STAT=$?

if [ $STAT -ne 0 ]
then
  echo "Program exited with error status"
fi
